/* ===============================
arrays
=============================== */
const questPrapor = [
	'Debut',
	'Search Mission',
	'Checking',
	'Shootout Picnic',
	'Delivery from the Past',
	'BP Depot',
	'The Bunker - Part 1',
	'The Bunker - Part 2',
	'Bad Rep Evidence',
	'Ice Cream Cones',
	'No Place for Renegades',
	'Documents',
	'Postman Pat - Part 1',
	'Shaking up the Teller',
	'The Punisher - Part 1',
	'The Punisher - Part 2',
	'The Punisher - Part 3',
	'The Punisher - Part 4',
	'The Punisher - Part 5',
	'The Punisher - Part 6',
	'Anesthesia',
	'Grenadier',
	'Insomnia',
	'Test Drive - Part 1',
	'Perfect Mediator',
	'Polikhim Hobo',
	'Regulated Materials',
	'Intimidator',
	'Easy Job - Part 1',
	'Easy Job - Part 2',
	'Reconnaissance',
];
const questTherapist = [
	'Shortage',
	'Operation Aquarius - Part 1',
	'Operation Aquarius - Part 2',
	'Sanitary Standards - Part 1',
	'Sanitary Standards - Part 2',
	'Painkiller',
	'Pharmacist',
	'Car Repair',
	'Disease History',
	'Health Care Privacy - Part 1',
	'Health Care Privacy - Part 2',
	'Health Care Privacy - Part 3',
	'Health Care Privacy - Part 4',
	'Athlete',
	'Private Clinic',
	'Health Care Privacy - Part 5',
	'Decontamination Service',
	'General Wares',
	'Colleagues - Part 1',
	'Colleagues - Part 2',
	'Postman Pat - Part 2',
	'Seaside Vacation',
	'Lost Contact',
	'Drug Trafficking',
];
const questSkier = [
	'Supplier',
	'The Extortionist',
	'Stirrup',
	'Whats on the Flash Drive?',
	'Golden Swag',
	'Chemical - Part 1',
	'Chemical - Part 2',
	'Chemical - Part 3',
	'Vitamins - Part 1',
	'Vitamins - Part 2',
	'Friend from the West - Part 1',
	'Friend from the West - Part 2',
	'Informed Means Armed',
	'Chumming',
	'Silent Caliber',
	'Bullshit',
	'Setup',
	'Flint',
	'Lend-Lease - Part 1',
	'Rigged Game',
	'Safe Corridor',
	'Long Road',
	'Missing Cargo',
];
const questPeacekeeper = [
	'Fishing Gear',
	'Tigr Safari',
	'Scrap Metal',
	'Eagle Eye',
	'Humanitarian Supplies',
	'The Cult - Part 1',
	'The Cult - Part 2',
	'Spa Tour - Part 1',
	'Spa Tour - Part 2',
	'Spa Tour - Part 3',
	'Spa Tour - Part 4',
	'Spa Tour - Part 5',
	'Spa Tour - Part 6',
	'Spa Tour - Part 7',
	'Cargo X - Part 1',
	'Cargo X - Part 2',
	'Cargo X - Part 3',
	'Wet Job - Part 1',
	'Wet Job - Part 2',
	'Wet Job - Part 3',
	'Wet Job - Part 4',
	'Wet Job - Part 5',
	'Wet Job - Part 6',
	'The Guide',
	'Samples',
	'TerraGroup Employee',
	'Lend-Lease - Part 2',
	'Peacekeeping Mission',
	'Classified Technologies',
	'Revision - Reserve',
	'Cargo X - Part 4',
	'Overpopulation',
	'Revision - Lighthouse',
];
const questMechanic = [
	'Introduction',
	'Gunsmith - Part 1',
	'Gunsmith - Part 2',
	'Gunsmith - Part 3',
	'Gunsmith - Part 4',
	'Gunsmith - Part 5',
	'Gunsmith - Part 6',
	'Gunsmith - Part 7',
	'Gunsmith - Part 8',
	'Gunsmith - Part 9',
	'Gunsmith - Part 10',
	'Gunsmith - Part 11',
	'Gunsmith - Part 12',
	'Gunsmith - Part 13',
	'Gunsmith - Part 14',
	'Gunsmith - Part 15',
	'Gunsmith - Part 16',
	'Gunsmith - Part 17',
	'Gunsmith - Part 18',
	'Gunsmith - Part 19',
	'Gunsmith - Part 20',
	'Gunsmith - Part 21',
	'Gunsmith - Part 22',
	'Signal - Part 1',
	'Insider',
	'Signal - Part 2',
	'Scout',
	'Surplus Goods',
	'Back Door',
	'Signal - Part 3',
	'Signal - Part 4',
	'Farming - Part 1',
	'Farming - Part 2',
	'Bad Habit',
	'Farming - Part 3',
	'Farming - Part 4',
	'Psycho Sniper',
	'A Shooter Born in Heaven',
	'Fertilizers',
	'Import',
	'Chemistry Closet',
	'Corporate Secrets',
	'Energy Crisis',
	'Broadcast - Part 1',
];
const questRagman = [
	'Only Business',
	'Make ULTRA Great Again',
	'Big Sale',
	'A Fuel Matter',
	'Inventory Check',
	'The Blood of War - Part 1',
	'Dressed to Kill',
	'Gratitude',
	'Hot Delivery',
	'Scavenger',
	'Sales Night',
	'Database - Part 1',
	'Database - Part 2',
	'Minibus',
	'Sew it Good - Part 1',
	'The Blood of War - Part 2',
	'The Blood of War - Part 3',
	'Sew it Good - Part 2',
	'The Key to Success',
	'No Fuss Needed',
	'Supervisor',
	'Sew it Good - Part 3',
	'Living High is Not a Crime - Part 1',
	'Living High is Not a Crime - Part 2',
	'Sew it Good - Part 4',
	'Charisma Brings Success',
	'Long Line',
	'Booze',
];
const questJaeger = [
	'Acquaintance',
	'The Survivalist Path - Unprotected but Dangerous',
	'The Survivalist Path - Thrifty',
	'The Survivalist Path - Zhivchik',
	'The Survivalist Path - Wounded Beast',
	'The Survivalist Path - Tough Guy',
	'Courtesy Visit',
	'Nostalgia',
	'The Survivalist Path - Cold Blooded',
	'The Survivalist Path - Junkie',
	'The Survivalist Path - Eagle-Owl',
	'The Survivalist Path - Combat Medic',
	'Ambulance',
	'The Huntsman Path - Secured Perimeter',
	'Reserve',
	'The Huntsman Path - Forest Cleaning',
	'The Huntsman Path - Controller',
	'The Huntsman Path - Evil Watchman',
	'Fishing Place',
	'The Huntsman Path - Trophy',
	'The Huntsman Path - Justice',
	'The Huntsman Path - Sellout',
	'The Huntsman Path - Woods Keeper',
	'Hunting Trip',
	'The Huntsman Path - Factory Chief',
	'The Huntsman Path - Eraser - Part 1',
	'The Huntsman Path - Eraser - Part 2',
	'The Tarkov Shooter - Part 1',
	'The Tarkov Shooter - Part 2',
	'The Tarkov Shooter - Part 3',
	'The Tarkov Shooter - Part 4',
	'The Tarkov Shooter - Part 5',
	'The Tarkov Shooter - Part 6',
	'The Tarkov Shooter - Part 7',
	'The Tarkov Shooter - Part 8',
	'Shady Business',
	'Pest Control',
	'The Hermit',
	'The Huntsman Path - Outcasts',
	'Stray Dogs',
	'The Delicious Sausage',
];
const totalOfTasks = [
	...questPrapor,
	...questTherapist,
	...questSkier,
	...questPeacekeeper,
	...questMechanic,
	...questRagman,
	...questJaeger,
];
/* ===============================
variables
=============================== */
const allQuests = document.querySelector('[data-allQuestToKappa]');
/* ===============================
functions
=============================== */
const allTasks = () => {
	const showTasks = totalOfTasks.length;
	allQuests.innerText = showTasks;
};
/* ===============================
activation of the function
=============================== */
document.addEventListener('DOMContentLoaded', allTasks);
